CREATE TABLE art_table_field_details (
  field_id varchar2(64) NOT NULL ,
  table_id varchar2(64) NOT NULL ,
  field_name varchar2(256) NOT NULL,
  data_type varchar2(256) NOT NULL,
  datatype_precision varchar2(45) DEFAULT NULL,
  is_pkey number(3) DEFAULT '0' NOT NULL,
  is_null number(3) DEFAULT '1' NOT NULL,
  is_auto_inc number(3) DEFAULT '0' NOT NULL,
  is_unique number(3) DEFAULT '0' NOT NULL,
  is_fkey number(3) DEFAULT '0' NOT NULL,
  reff_key varchar2(256) DEFAULT NULL,
  reff_table varchar2(256) DEFAULT NULL,
  primary_display number(3) DEFAULT NULL,
  default_value varchar2(256) DEFAULT NULL,
  system_field number(3) DEFAULT '0' NOT NULL,
  column_sequence varchar2(256) DEFAULT NULL,
  display_json clob,
  project_id varchar2(256) NOT NULL,
  app_creator_id varchar2(256) NOT NULL,
  project_version_id varchar2(256) DEFAULT NULL,
  created_by number(10) DEFAULT NULL,
  created_date timestamp(0) DEFAULT NULL,
  updated_by number(10) DEFAULT NULL,
  updated_date timestamp(0) DEFAULT NULL,
  version_id number(10) DEFAULT NULL,
  active_status number(3) DEFAULT '1',
  field_order number(10) DEFAULT NULL,
  field_group varchar2(256) DEFAULT NULL,
  target_field varchar2(256) DEFAULT NULL,
  transient_field number(3) DEFAULT NULL,
  ui_permission number(10) DEFAULT '0',
  PRIMARY KEY (field_id),
  CONSTRAINT uniqueID UNIQUE  (table_id,field_name),
  CONSTRAINT FK FOREIGN KEY (table_id) REFERENCES art_table_details (table_id)
);

exit

