CREATE TABLE zen_health (
  monitor_id varchar2(64) NOT NULL ,
  class_Unloaded number(10) NOT NULL,
  gc_Collection_Time number(10) NOT NULL,
  non_Heap_Committed number(19) NOT NULL,
  start_Time timestamp(0) NOT NULL,
  cpu_Time binary_double NOT NULL,
  cpu_Load_Time binary_double DEFAULT '0' NOT NULL,
  non_Heap_used number(19) NOT NULL,
  up_Time number(10) NOT NULL,
  free_Physical_Size number(19) NOT NULL,
  total_Thread binary_double NOT NULL,
  heap_Committed number(19) NOT NULL,
  total_Physical_Memory_Size number(19) NOT NULL,
  thread_Peak_Count binary_double NOT NULL,
  scheduled_DateTime timestamp(0) NOT NULL,
  max_Memory number(19) NOT NULL,
  cpu_Load binary_double DEFAULT '0' NOT NULL,
  thread_Started_Count binary_double NOT NULL,
  thread_Daemon_Count binary_double NOT NULL,
  server_Instance_Id number(10) NOT NULL,
  total_Class varchar2(256) NOT NULL,
  free_Memory number(19) NOT NULL,
  free_Swap_Size number(19) NOT NULL,
  server_Ip_Address varchar2(30) NOT NULL,
  class_Loaded varchar2(32) NOT NULL,
  heap_Used number(19) NOT NULL,
  system_Load_Average binary_double NOT NULL,
  thread_Cpu_Time binary_double NOT NULL,
  total_Memory number(19) NOT NULL,
  total_Swap_Size number(19) NOT NULL,
  available_Processor binary_double NOT NULL,
  gc_Memory_Name varchar2(256) NOT NULL,
  thread_User_Time varchar2(45) DEFAULT NULL,
  used_Memory number(19) DEFAULT NULL,
  used_Swap_Size number(19) DEFAULT NULL,
  used_Physical_Memory number(19) DEFAULT NULL,
  PRIMARY KEY (monitor_id)
);

exit

